export type ThemeCategory = "purple" | "blue" | "black" | "green" | "red" | "amber" | "teal"

export type Palette = {
  background: string
  foreground: string
  card: string
  "card-foreground": string
  popover: string
  "popover-foreground": string
  primary: string
  "primary-foreground": string
  secondary: string
  "secondary-foreground": string
  muted: string
  "muted-foreground": string
  accent: string
  "accent-foreground": string
  destructive: string
  "destructive-foreground": string
  success: string
  "success-foreground": string
  warning: string
  "warning-foreground": string
  border: string
  input: string
  ring: string
}

export type Theme = {
  id: string
  name: string
  category: ThemeCategory
  mode: "dark" | "light"
  swatchBg: string
  swatchPrimary: string
  swatchAccent: string
  palette: Palette
}

function hslToHex(h: number, s: number, l: number): string {
  const sPct = s / 100
  const lPct = l / 100
  const c = (1 - Math.abs(2 * lPct - 1)) * sPct
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1))
  const m = lPct - c / 2
  let r = 0
  let g = 0
  let b = 0
  if (h < 60) [r, g, b] = [c, x, 0]
  else if (h < 120) [r, g, b] = [x, c, 0]
  else if (h < 180) [r, g, b] = [0, c, x]
  else if (h < 240) [r, g, b] = [0, x, c]
  else if (h < 300) [r, g, b] = [x, 0, c]
  else [r, g, b] = [c, 0, x]
  const toHex = (v: number) =>
    Math.round((v + m) * 255)
      .toString(16)
      .padStart(2, "0")
  return `#${toHex(r)}${toHex(g)}${toHex(b)}`
}

type DarkSpec = {
  id: string
  name: string
  category: ThemeCategory
  bgHue: number
  bgSat: number
  bgLight: number
  primaryHue: number
  primarySat: number
  primaryLight: number
}

function makeDark(s: DarkSpec): Theme {
  const { bgHue, bgSat, bgLight, primaryHue, primarySat, primaryLight } = s
  const surfaceLight = Math.min(bgLight + 4, 22)
  const elevatedLight = Math.min(bgLight + 8, 28)
  const accentLight = Math.min(bgLight + 14, 34)
  const borderLight = Math.min(bgLight + 10, 30)
  const fgSat = Math.min(bgSat + 15, 55)
  const fgLight = 92
  const mutedFgSat = Math.max(Math.floor(bgSat * 0.6), 10)
  const mutedFgLight = 65

  const hsl = (h: number, sat: number, light: number) => `${h} ${sat}% ${light}%`

  return {
    id: s.id,
    name: s.name,
    category: s.category,
    mode: "dark",
    swatchBg: hslToHex(bgHue, bgSat, bgLight),
    swatchPrimary: hslToHex(primaryHue, primarySat, primaryLight),
    swatchAccent: hslToHex(bgHue, bgSat, accentLight),
    palette: {
      background: hsl(bgHue, bgSat, bgLight),
      foreground: hsl(bgHue, fgSat, fgLight),
      card: hsl(bgHue, bgSat, surfaceLight),
      "card-foreground": hsl(bgHue, fgSat, fgLight),
      popover: hsl(bgHue, bgSat, surfaceLight),
      "popover-foreground": hsl(bgHue, fgSat, fgLight),
      primary: hsl(primaryHue, primarySat, primaryLight),
      "primary-foreground": primaryLight > 60 ? hsl(bgHue, bgSat, bgLight) : "0 0% 100%",
      secondary: hsl(bgHue, Math.floor(bgSat * 0.85), elevatedLight),
      "secondary-foreground": hsl(bgHue, fgSat, fgLight),
      muted: hsl(bgHue, Math.floor(bgSat * 0.85), elevatedLight),
      "muted-foreground": hsl(bgHue, mutedFgSat, mutedFgLight),
      accent: hsl(bgHue, bgSat, accentLight),
      "accent-foreground": hsl(bgHue, fgSat, fgLight),
      destructive: "0 75% 60%",
      "destructive-foreground": "0 0% 100%",
      success: "142 60% 50%",
      "success-foreground": "0 0% 100%",
      warning: "38 90% 58%",
      "warning-foreground": "0 0% 10%",
      border: hsl(bgHue, Math.floor(bgSat * 0.8), borderLight),
      input: hsl(bgHue, Math.floor(bgSat * 0.8), borderLight),
      ring: hsl(primaryHue, primarySat, primaryLight),
    },
  }
}

const purpleThemes: Theme[] = [
  makeDark({
    id: "purple-royal",
    name: "Royal Purple",
    category: "purple",
    bgHue: 270,
    bgSat: 30,
    bgLight: 12,
    primaryHue: 270,
    primarySat: 75,
    primaryLight: 65,
  }),
  makeDark({
    id: "purple-eggplant",
    name: "Eggplant",
    category: "purple",
    bgHue: 291,
    bgSat: 35,
    bgLight: 15,
    primaryHue: 280,
    primarySat: 75,
    primaryLight: 68,
  }),
  makeDark({
    id: "purple-midnight-plum",
    name: "Midnight Plum",
    category: "purple",
    bgHue: 280,
    bgSat: 40,
    bgLight: 10,
    primaryHue: 285,
    primarySat: 80,
    primaryLight: 70,
  }),
  makeDark({
    id: "purple-deep-violet",
    name: "Deep Violet",
    category: "purple",
    bgHue: 260,
    bgSat: 45,
    bgLight: 11,
    primaryHue: 265,
    primarySat: 80,
    primaryLight: 68,
  }),
  makeDark({
    id: "purple-amethyst",
    name: "Amethyst",
    category: "purple",
    bgHue: 275,
    bgSat: 38,
    bgLight: 14,
    primaryHue: 275,
    primarySat: 70,
    primaryLight: 64,
  }),
  makeDark({
    id: "purple-aubergine",
    name: "Aubergine",
    category: "purple",
    bgHue: 295,
    bgSat: 30,
    bgLight: 13,
    primaryHue: 290,
    primarySat: 70,
    primaryLight: 66,
  }),
  makeDark({
    id: "purple-mulberry",
    name: "Mulberry",
    category: "purple",
    bgHue: 310,
    bgSat: 32,
    bgLight: 14,
    primaryHue: 305,
    primarySat: 70,
    primaryLight: 65,
  }),
  makeDark({
    id: "purple-wine",
    name: "Wine Purple",
    category: "purple",
    bgHue: 320,
    bgSat: 30,
    bgLight: 13,
    primaryHue: 315,
    primarySat: 70,
    primaryLight: 60,
  }),
  makeDark({
    id: "purple-indigo-night",
    name: "Indigo Night",
    category: "purple",
    bgHue: 250,
    bgSat: 38,
    bgLight: 12,
    primaryHue: 255,
    primarySat: 75,
    primaryLight: 68,
  }),
  makeDark({
    id: "purple-wisteria",
    name: "Wisteria",
    category: "purple",
    bgHue: 265,
    bgSat: 25,
    bgLight: 16,
    primaryHue: 265,
    primarySat: 65,
    primaryLight: 70,
  }),
  makeDark({
    id: "purple-iris",
    name: "Iris",
    category: "purple",
    bgHue: 257,
    bgSat: 35,
    bgLight: 13,
    primaryHue: 260,
    primarySat: 78,
    primaryLight: 66,
  }),
  makeDark({
    id: "purple-orchid",
    name: "Orchid",
    category: "purple",
    bgHue: 300,
    bgSat: 28,
    bgLight: 14,
    primaryHue: 300,
    primarySat: 70,
    primaryLight: 70,
  }),
  makeDark({
    id: "purple-mauve-deep",
    name: "Deep Mauve",
    category: "purple",
    bgHue: 285,
    bgSat: 25,
    bgLight: 16,
    primaryHue: 285,
    primarySat: 60,
    primaryLight: 72,
  }),
  makeDark({
    id: "purple-plum-velvet",
    name: "Plum Velvet",
    category: "purple",
    bgHue: 305,
    bgSat: 35,
    bgLight: 11,
    primaryHue: 300,
    primarySat: 75,
    primaryLight: 65,
  }),
  makeDark({
    id: "purple-grape",
    name: "Grape Night",
    category: "purple",
    bgHue: 277,
    bgSat: 42,
    bgLight: 12,
    primaryHue: 280,
    primarySat: 80,
    primaryLight: 67,
  }),
  makeDark({
    id: "purple-boysenberry",
    name: "Boysenberry",
    category: "purple",
    bgHue: 315,
    bgSat: 38,
    bgLight: 12,
    primaryHue: 320,
    primarySat: 75,
    primaryLight: 65,
  }),
  makeDark({
    id: "purple-magenta-dark",
    name: "Magenta Dark",
    category: "purple",
    bgHue: 320,
    bgSat: 45,
    bgLight: 11,
    primaryHue: 325,
    primarySat: 80,
    primaryLight: 65,
  }),
  makeDark({
    id: "purple-fuchsia-deep",
    name: "Deep Fuchsia",
    category: "purple",
    bgHue: 308,
    bgSat: 50,
    bgLight: 12,
    primaryHue: 310,
    primarySat: 85,
    primaryLight: 65,
  }),
  makeDark({
    id: "purple-byzantine",
    name: "Byzantine",
    category: "purple",
    bgHue: 305,
    bgSat: 55,
    bgLight: 13,
    primaryHue: 300,
    primarySat: 80,
    primaryLight: 60,
  }),
  makeDark({
    id: "purple-tyrian",
    name: "Tyrian Purple",
    category: "purple",
    bgHue: 295,
    bgSat: 55,
    bgLight: 14,
    primaryHue: 300,
    primarySat: 85,
    primaryLight: 55,
  }),
  makeDark({
    id: "purple-imperial",
    name: "Imperial Purple",
    category: "purple",
    bgHue: 270,
    bgSat: 50,
    bgLight: 13,
    primaryHue: 275,
    primarySat: 80,
    primaryLight: 60,
  }),
  makeDark({
    id: "purple-cosmic",
    name: "Cosmic Purple",
    category: "purple",
    bgHue: 263,
    bgSat: 60,
    bgLight: 11,
    primaryHue: 270,
    primarySat: 90,
    primaryLight: 70,
  }),
  makeDark({
    id: "purple-twilight",
    name: "Twilight Purple",
    category: "purple",
    bgHue: 268,
    bgSat: 28,
    bgLight: 15,
    primaryHue: 268,
    primarySat: 65,
    primaryLight: 70,
  }),
  makeDark({
    id: "purple-bruised-plum",
    name: "Bruised Plum",
    category: "purple",
    bgHue: 290,
    bgSat: 28,
    bgLight: 11,
    primaryHue: 285,
    primarySat: 60,
    primaryLight: 60,
  }),
  makeDark({
    id: "purple-smoky",
    name: "Smoky Purple",
    category: "purple",
    bgHue: 275,
    bgSat: 18,
    bgLight: 14,
    primaryHue: 275,
    primarySat: 55,
    primaryLight: 68,
  }),
  makeDark({
    id: "purple-mystic-violet",
    name: "Mystic Violet",
    category: "purple",
    bgHue: 262,
    bgSat: 40,
    bgLight: 9,
    primaryHue: 270,
    primarySat: 85,
    primaryLight: 72,
  }),
  makeDark({
    id: "purple-galactic",
    name: "Galactic",
    category: "purple",
    bgHue: 258,
    bgSat: 50,
    bgLight: 8,
    primaryHue: 265,
    primarySat: 85,
    primaryLight: 68,
  }),
  makeDark({
    id: "purple-301934",
    name: "Dark Plum #301934",
    category: "purple",
    bgHue: 291,
    bgSat: 35,
    bgLight: 15,
    primaryHue: 280,
    primarySat: 75,
    primaryLight: 68,
  }),
  makeDark({
    id: "purple-violet-ink",
    name: "Violet Ink",
    category: "purple",
    bgHue: 252,
    bgSat: 35,
    bgLight: 13,
    primaryHue: 258,
    primarySat: 75,
    primaryLight: 70,
  }),
  makeDark({
    id: "purple-blackberry",
    name: "Blackberry",
    category: "purple",
    bgHue: 285,
    bgSat: 35,
    bgLight: 9,
    primaryHue: 285,
    primarySat: 70,
    primaryLight: 65,
  }),
]

const blueThemes: Theme[] = [
  makeDark({
    id: "blue-midnight",
    name: "Midnight Blue",
    category: "blue",
    bgHue: 220,
    bgSat: 38,
    bgLight: 12,
    primaryHue: 215,
    primarySat: 85,
    primaryLight: 65,
  }),
  makeDark({
    id: "blue-royal",
    name: "Royal Blue",
    category: "blue",
    bgHue: 225,
    bgSat: 50,
    bgLight: 13,
    primaryHue: 220,
    primarySat: 90,
    primaryLight: 62,
  }),
  makeDark({
    id: "blue-sapphire",
    name: "Sapphire Dark",
    category: "blue",
    bgHue: 215,
    bgSat: 60,
    bgLight: 12,
    primaryHue: 210,
    primarySat: 85,
    primaryLight: 60,
  }),
  makeDark({
    id: "blue-cobalt",
    name: "Cobalt Night",
    category: "blue",
    bgHue: 225,
    bgSat: 70,
    bgLight: 11,
    primaryHue: 220,
    primarySat: 90,
    primaryLight: 60,
  }),
  makeDark({
    id: "blue-prussian",
    name: "Prussian Blue",
    category: "blue",
    bgHue: 210,
    bgSat: 50,
    bgLight: 10,
    primaryHue: 205,
    primarySat: 80,
    primaryLight: 60,
  }),
  makeDark({
    id: "blue-navy",
    name: "Navy Black",
    category: "blue",
    bgHue: 220,
    bgSat: 35,
    bgLight: 8,
    primaryHue: 215,
    primarySat: 80,
    primaryLight: 65,
  }),
  makeDark({
    id: "blue-ocean",
    name: "Ocean Deep",
    category: "blue",
    bgHue: 205,
    bgSat: 50,
    bgLight: 11,
    primaryHue: 200,
    primarySat: 85,
    primaryLight: 60,
  }),
  makeDark({
    id: "blue-indigo",
    name: "Indigo Blue",
    category: "blue",
    bgHue: 235,
    bgSat: 45,
    bgLight: 13,
    primaryHue: 230,
    primarySat: 80,
    primaryLight: 65,
  }),
  makeDark({
    id: "blue-cerulean",
    name: "Cerulean Dark",
    category: "blue",
    bgHue: 200,
    bgSat: 55,
    bgLight: 12,
    primaryHue: 195,
    primarySat: 85,
    primaryLight: 60,
  }),
  makeDark({
    id: "blue-steel",
    name: "Steel Blue",
    category: "blue",
    bgHue: 210,
    bgSat: 25,
    bgLight: 14,
    primaryHue: 210,
    primarySat: 65,
    primaryLight: 65,
  }),
  makeDark({
    id: "blue-slate",
    name: "Slate Blue",
    category: "blue",
    bgHue: 215,
    bgSat: 20,
    bgLight: 14,
    primaryHue: 215,
    primarySat: 55,
    primaryLight: 65,
  }),
  makeDark({
    id: "blue-iceberg",
    name: "Iceberg",
    category: "blue",
    bgHue: 200,
    bgSat: 30,
    bgLight: 13,
    primaryHue: 195,
    primarySat: 70,
    primaryLight: 70,
  }),
  makeDark({
    id: "blue-storm",
    name: "Storm Blue",
    category: "blue",
    bgHue: 218,
    bgSat: 28,
    bgLight: 14,
    primaryHue: 215,
    primarySat: 70,
    primaryLight: 65,
  }),
  makeDark({
    id: "blue-twilight",
    name: "Twilight Blue",
    category: "blue",
    bgHue: 232,
    bgSat: 35,
    bgLight: 13,
    primaryHue: 228,
    primarySat: 75,
    primaryLight: 70,
  }),
  makeDark({
    id: "blue-dusk",
    name: "Dusk Blue",
    category: "blue",
    bgHue: 228,
    bgSat: 25,
    bgLight: 15,
    primaryHue: 225,
    primarySat: 65,
    primaryLight: 72,
  }),
  makeDark({
    id: "blue-glacier",
    name: "Glacier",
    category: "blue",
    bgHue: 205,
    bgSat: 35,
    bgLight: 14,
    primaryHue: 195,
    primarySat: 80,
    primaryLight: 75,
  }),
  makeDark({
    id: "blue-arctic",
    name: "Arctic Blue",
    category: "blue",
    bgHue: 198,
    bgSat: 40,
    bgLight: 13,
    primaryHue: 192,
    primarySat: 80,
    primaryLight: 70,
  }),
  makeDark({
    id: "blue-phthalo",
    name: "Phthalo Blue",
    category: "blue",
    bgHue: 215,
    bgSat: 70,
    bgLight: 9,
    primaryHue: 210,
    primarySat: 85,
    primaryLight: 60,
  }),
  makeDark({
    id: "blue-yale",
    name: "Yale Blue",
    category: "blue",
    bgHue: 215,
    bgSat: 60,
    bgLight: 14,
    primaryHue: 210,
    primarySat: 80,
    primaryLight: 65,
  }),
  makeDark({
    id: "blue-oxford",
    name: "Oxford Blue",
    category: "blue",
    bgHue: 220,
    bgSat: 55,
    bgLight: 9,
    primaryHue: 215,
    primarySat: 80,
    primaryLight: 65,
  }),
  makeDark({
    id: "blue-egyptian",
    name: "Egyptian Blue",
    category: "blue",
    bgHue: 220,
    bgSat: 75,
    bgLight: 13,
    primaryHue: 220,
    primarySat: 95,
    primaryLight: 65,
  }),
  makeDark({
    id: "blue-klein",
    name: "Klein Blue",
    category: "blue",
    bgHue: 230,
    bgSat: 80,
    bgLight: 14,
    primaryHue: 228,
    primarySat: 95,
    primaryLight: 60,
  }),
  makeDark({
    id: "blue-persian",
    name: "Persian Blue",
    category: "blue",
    bgHue: 222,
    bgSat: 65,
    bgLight: 13,
    primaryHue: 220,
    primarySat: 85,
    primaryLight: 65,
  }),
  makeDark({
    id: "blue-cyan-dark",
    name: "Cyan Dark",
    category: "blue",
    bgHue: 188,
    bgSat: 55,
    bgLight: 11,
    primaryHue: 185,
    primarySat: 85,
    primaryLight: 60,
  }),
  makeDark({
    id: "blue-tokyo-night",
    name: "Tokyo Night",
    category: "blue",
    bgHue: 232,
    bgSat: 21,
    bgLight: 13,
    primaryHue: 218,
    primarySat: 89,
    primaryLight: 72,
  }),
  makeDark({
    id: "blue-velvet",
    name: "Navy Velvet",
    category: "blue",
    bgHue: 225,
    bgSat: 42,
    bgLight: 11,
    primaryHue: 218,
    primarySat: 80,
    primaryLight: 68,
  }),
  makeDark({
    id: "blue-blueprint",
    name: "Blueprint",
    category: "blue",
    bgHue: 215,
    bgSat: 45,
    bgLight: 16,
    primaryHue: 210,
    primarySat: 80,
    primaryLight: 70,
  }),
  makeDark({
    id: "blue-frost",
    name: "Frost",
    category: "blue",
    bgHue: 210,
    bgSat: 22,
    bgLight: 16,
    primaryHue: 205,
    primarySat: 70,
    primaryLight: 72,
  }),
  makeDark({
    id: "blue-azure-deep",
    name: "Deep Azure",
    category: "blue",
    bgHue: 210,
    bgSat: 55,
    bgLight: 10,
    primaryHue: 205,
    primarySat: 85,
    primaryLight: 60,
  }),
  makeDark({
    id: "blue-cornflower",
    name: "Cornflower Dark",
    category: "blue",
    bgHue: 218,
    bgSat: 30,
    bgLight: 13,
    primaryHue: 218,
    primarySat: 75,
    primaryLight: 70,
  }),
]

const blackThemes: Theme[] = [
  makeDark({
    id: "black-pure",
    name: "Pure Black",
    category: "black",
    bgHue: 0,
    bgSat: 0,
    bgLight: 0,
    primaryHue: 0,
    primarySat: 0,
    primaryLight: 95,
  }),
  makeDark({
    id: "black-onyx",
    name: "Onyx",
    category: "black",
    bgHue: 0,
    bgSat: 0,
    bgLight: 4,
    primaryHue: 0,
    primarySat: 0,
    primaryLight: 93,
  }),
  makeDark({
    id: "black-obsidian",
    name: "Obsidian",
    category: "black",
    bgHue: 0,
    bgSat: 0,
    bgLight: 6,
    primaryHue: 0,
    primarySat: 0,
    primaryLight: 90,
  }),
  makeDark({
    id: "black-charcoal",
    name: "Charcoal",
    category: "black",
    bgHue: 0,
    bgSat: 0,
    bgLight: 9,
    primaryHue: 0,
    primarySat: 0,
    primaryLight: 88,
  }),
  makeDark({
    id: "black-graphite",
    name: "Graphite",
    category: "black",
    bgHue: 0,
    bgSat: 0,
    bgLight: 11,
    primaryHue: 0,
    primarySat: 0,
    primaryLight: 86,
  }),
  makeDark({
    id: "black-slate-gray",
    name: "Slate Gray",
    category: "black",
    bgHue: 220,
    bgSat: 8,
    bgLight: 12,
    primaryHue: 220,
    primarySat: 5,
    primaryLight: 85,
  }),
  makeDark({
    id: "black-pitch",
    name: "Pitch Black",
    category: "black",
    bgHue: 0,
    bgSat: 0,
    bgLight: 2,
    primaryHue: 0,
    primarySat: 0,
    primaryLight: 96,
  }),
  makeDark({
    id: "black-carbon",
    name: "Carbon",
    category: "black",
    bgHue: 210,
    bgSat: 5,
    bgLight: 9,
    primaryHue: 210,
    primarySat: 5,
    primaryLight: 85,
  }),
  makeDark({
    id: "black-anthracite",
    name: "Anthracite",
    category: "black",
    bgHue: 200,
    bgSat: 6,
    bgLight: 11,
    primaryHue: 200,
    primarySat: 5,
    primaryLight: 80,
  }),
  makeDark({
    id: "black-ebony",
    name: "Ebony",
    category: "black",
    bgHue: 30,
    bgSat: 8,
    bgLight: 6,
    primaryHue: 30,
    primarySat: 10,
    primaryLight: 85,
  }),
  makeDark({
    id: "black-jet",
    name: "Jet Black",
    category: "black",
    bgHue: 0,
    bgSat: 0,
    bgLight: 3,
    primaryHue: 0,
    primarySat: 0,
    primaryLight: 92,
  }),
  makeDark({
    id: "black-soft",
    name: "Soft Black",
    category: "black",
    bgHue: 0,
    bgSat: 0,
    bgLight: 8,
    primaryHue: 0,
    primarySat: 0,
    primaryLight: 85,
  }),
  makeDark({
    id: "black-mineral",
    name: "Mineral",
    category: "black",
    bgHue: 200,
    bgSat: 8,
    bgLight: 14,
    primaryHue: 200,
    primarySat: 10,
    primaryLight: 80,
  }),
  makeDark({
    id: "black-off",
    name: "Off-Black",
    category: "black",
    bgHue: 220,
    bgSat: 6,
    bgLight: 7,
    primaryHue: 220,
    primarySat: 8,
    primaryLight: 88,
  }),
  makeDark({
    id: "black-asphalt",
    name: "Asphalt",
    category: "black",
    bgHue: 210,
    bgSat: 8,
    bgLight: 13,
    primaryHue: 210,
    primarySat: 6,
    primaryLight: 82,
  }),
  makeDark({
    id: "black-shadow",
    name: "Shadow",
    category: "black",
    bgHue: 0,
    bgSat: 0,
    bgLight: 5,
    primaryHue: 0,
    primarySat: 0,
    primaryLight: 80,
  }),
  makeDark({
    id: "black-stealth",
    name: "Stealth",
    category: "black",
    bgHue: 220,
    bgSat: 10,
    bgLight: 5,
    primaryHue: 220,
    primarySat: 15,
    primaryLight: 85,
  }),
]

const greenThemes: Theme[] = [
  makeDark({
    id: "green-forest",
    name: "Forest",
    category: "green",
    bgHue: 140,
    bgSat: 25,
    bgLight: 11,
    primaryHue: 140,
    primarySat: 60,
    primaryLight: 55,
  }),
  makeDark({
    id: "green-emerald",
    name: "Emerald",
    category: "green",
    bgHue: 155,
    bgSat: 35,
    bgLight: 11,
    primaryHue: 150,
    primarySat: 70,
    primaryLight: 55,
  }),
  makeDark({
    id: "green-pine",
    name: "Pine",
    category: "green",
    bgHue: 145,
    bgSat: 30,
    bgLight: 9,
    primaryHue: 145,
    primarySat: 55,
    primaryLight: 50,
  }),
  makeDark({
    id: "green-hunter",
    name: "Hunter",
    category: "green",
    bgHue: 130,
    bgSat: 28,
    bgLight: 11,
    primaryHue: 130,
    primarySat: 50,
    primaryLight: 55,
  }),
  makeDark({
    id: "green-jade",
    name: "Jade Dark",
    category: "green",
    bgHue: 160,
    bgSat: 35,
    bgLight: 12,
    primaryHue: 160,
    primarySat: 65,
    primaryLight: 55,
  }),
  makeDark({
    id: "green-moss",
    name: "Moss",
    category: "green",
    bgHue: 100,
    bgSat: 22,
    bgLight: 12,
    primaryHue: 105,
    primarySat: 50,
    primaryLight: 55,
  }),
  makeDark({
    id: "green-mint-dark",
    name: "Dark Mint",
    category: "green",
    bgHue: 170,
    bgSat: 30,
    bgLight: 12,
    primaryHue: 165,
    primarySat: 65,
    primaryLight: 60,
  }),
  makeDark({
    id: "green-olive",
    name: "Olive Dark",
    category: "green",
    bgHue: 75,
    bgSat: 22,
    bgLight: 12,
    primaryHue: 80,
    primarySat: 50,
    primaryLight: 55,
  }),
  makeDark({
    id: "green-pine-velvet",
    name: "Pine Velvet",
    category: "green",
    bgHue: 150,
    bgSat: 35,
    bgLight: 8,
    primaryHue: 150,
    primarySat: 60,
    primaryLight: 55,
  }),
  makeDark({
    id: "green-matrix",
    name: "Matrix",
    category: "green",
    bgHue: 120,
    bgSat: 25,
    bgLight: 6,
    primaryHue: 120,
    primarySat: 90,
    primaryLight: 50,
  }),
]

const tealThemes: Theme[] = [
  makeDark({
    id: "teal-deep",
    name: "Deep Teal",
    category: "teal",
    bgHue: 180,
    bgSat: 35,
    bgLight: 11,
    primaryHue: 180,
    primarySat: 75,
    primaryLight: 55,
  }),
  makeDark({
    id: "teal-ocean",
    name: "Ocean Teal",
    category: "teal",
    bgHue: 188,
    bgSat: 40,
    bgLight: 12,
    primaryHue: 185,
    primarySat: 75,
    primaryLight: 55,
  }),
  makeDark({
    id: "teal-aqua",
    name: "Aqua Dark",
    category: "teal",
    bgHue: 175,
    bgSat: 30,
    bgLight: 13,
    primaryHue: 175,
    primarySat: 70,
    primaryLight: 60,
  }),
  makeDark({
    id: "teal-lagoon",
    name: "Lagoon",
    category: "teal",
    bgHue: 182,
    bgSat: 38,
    bgLight: 14,
    primaryHue: 182,
    primarySat: 75,
    primaryLight: 60,
  }),
  makeDark({
    id: "teal-seafoam-dark",
    name: "Dark Seafoam",
    category: "teal",
    bgHue: 170,
    bgSat: 28,
    bgLight: 13,
    primaryHue: 168,
    primarySat: 65,
    primaryLight: 60,
  }),
]

const redThemes: Theme[] = [
  makeDark({
    id: "red-wine",
    name: "Wine",
    category: "red",
    bgHue: 350,
    bgSat: 35,
    bgLight: 12,
    primaryHue: 350,
    primarySat: 75,
    primaryLight: 60,
  }),
  makeDark({
    id: "red-burgundy",
    name: "Burgundy",
    category: "red",
    bgHue: 345,
    bgSat: 40,
    bgLight: 11,
    primaryHue: 345,
    primarySat: 70,
    primaryLight: 55,
  }),
  makeDark({
    id: "red-crimson",
    name: "Crimson Dark",
    category: "red",
    bgHue: 355,
    bgSat: 45,
    bgLight: 11,
    primaryHue: 355,
    primarySat: 80,
    primaryLight: 60,
  }),
  makeDark({
    id: "red-maroon",
    name: "Maroon",
    category: "red",
    bgHue: 0,
    bgSat: 35,
    bgLight: 11,
    primaryHue: 0,
    primarySat: 70,
    primaryLight: 60,
  }),
  makeDark({
    id: "red-rose-black",
    name: "Rose Black",
    category: "red",
    bgHue: 340,
    bgSat: 25,
    bgLight: 10,
    primaryHue: 340,
    primarySat: 75,
    primaryLight: 65,
  }),
  makeDark({
    id: "red-garnet",
    name: "Garnet",
    category: "red",
    bgHue: 350,
    bgSat: 50,
    bgLight: 11,
    primaryHue: 350,
    primarySat: 80,
    primaryLight: 55,
  }),
  makeDark({
    id: "red-oxblood",
    name: "Oxblood",
    category: "red",
    bgHue: 358,
    bgSat: 38,
    bgLight: 9,
    primaryHue: 358,
    primarySat: 70,
    primaryLight: 55,
  }),
  makeDark({
    id: "red-bordeaux",
    name: "Bordeaux",
    category: "red",
    bgHue: 345,
    bgSat: 32,
    bgLight: 13,
    primaryHue: 345,
    primarySat: 70,
    primaryLight: 58,
  }),
]

const amberThemes: Theme[] = [
  makeDark({
    id: "amber-coffee",
    name: "Coffee",
    category: "amber",
    bgHue: 25,
    bgSat: 28,
    bgLight: 11,
    primaryHue: 30,
    primarySat: 70,
    primaryLight: 60,
  }),
  makeDark({
    id: "amber-tobacco",
    name: "Tobacco",
    category: "amber",
    bgHue: 30,
    bgSat: 25,
    bgLight: 12,
    primaryHue: 35,
    primarySat: 65,
    primaryLight: 58,
  }),
  makeDark({
    id: "amber-mahogany",
    name: "Mahogany",
    category: "amber",
    bgHue: 15,
    bgSat: 35,
    bgLight: 12,
    primaryHue: 20,
    primarySat: 75,
    primaryLight: 58,
  }),
  makeDark({
    id: "amber-saffron",
    name: "Saffron Dark",
    category: "amber",
    bgHue: 40,
    bgSat: 30,
    bgLight: 12,
    primaryHue: 45,
    primarySat: 85,
    primaryLight: 60,
  }),
  makeDark({
    id: "amber-honey",
    name: "Honey Dark",
    category: "amber",
    bgHue: 38,
    bgSat: 28,
    bgLight: 13,
    primaryHue: 42,
    primarySat: 80,
    primaryLight: 60,
  }),
  makeDark({
    id: "amber-mustard",
    name: "Mustard Dark",
    category: "amber",
    bgHue: 48,
    bgSat: 32,
    bgLight: 12,
    primaryHue: 50,
    primarySat: 80,
    primaryLight: 55,
  }),
  makeDark({
    id: "amber-bronze",
    name: "Bronze",
    category: "amber",
    bgHue: 28,
    bgSat: 32,
    bgLight: 11,
    primaryHue: 32,
    primarySat: 70,
    primaryLight: 58,
  }),
]

export const themes: Theme[] = [
  ...purpleThemes,
  ...blueThemes,
  ...blackThemes,
  ...tealThemes,
  ...greenThemes,
  ...redThemes,
  ...amberThemes,
]

export const themesByCategory: Record<ThemeCategory, Theme[]> = {
  purple: purpleThemes,
  blue: blueThemes,
  black: blackThemes,
  teal: tealThemes,
  green: greenThemes,
  red: redThemes,
  amber: amberThemes,
}

export const categoryLabels: Record<ThemeCategory, string> = {
  purple: "Purple",
  blue: "Blue",
  black: "Black & Gray",
  teal: "Teal",
  green: "Green",
  red: "Red & Wine",
  amber: "Amber & Earth",
}

export function findTheme(id: string | null | undefined): Theme | undefined {
  if (!id) return undefined
  return themes.find((t) => t.id === id)
}

export const PALETTE_KEYS: Array<keyof Palette> = [
  "background",
  "foreground",
  "card",
  "card-foreground",
  "popover",
  "popover-foreground",
  "primary",
  "primary-foreground",
  "secondary",
  "secondary-foreground",
  "muted",
  "muted-foreground",
  "accent",
  "accent-foreground",
  "destructive",
  "destructive-foreground",
  "success",
  "success-foreground",
  "warning",
  "warning-foreground",
  "border",
  "input",
  "ring",
]
