-- AlterEnum: Add missing GoalStatus values
ALTER TYPE "GoalStatus" ADD VALUE IF NOT EXISTS 'NOT_STARTED' BEFORE 'ACTIVE';
ALTER TYPE "GoalStatus" ADD VALUE IF NOT EXISTS 'IN_PROGRESS' BEFORE 'COMPLETED';
